extends:
  - react-app
  - airbnb-base

ignorePatterns:
  - node_modules
  - test

rules:
  semi:
    - warn
    - always
  indent:
    - error
    - 2
    - SwitchCase: 1
      FunctionDeclaration: 
        parameters: first
      FunctionExpression:
        parameters: first
      CallExpression:
        arguments: first
  object-curly-newline: off
  curly:
    - error
    - all
  function-paren-newline: off
  no-async-promise-executor: off
  no-await-in-loop: off
  linebreak-style: off
